# Site settings
title: Amorphous Solid
email: gsarjeant@amorphoussolid.net
description: > # this means to ignore newlines until "baseurl:"
        Ill-defined by design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gsarjeant.github.io" # the base hostname & protocol for your site
twitter_username: gregsarjeant
github_username: gsarjeant

# Build settings
markdown: kramdown
