plugins:
  - jekyll-feed
  - jekyll-remote-theme
title: Subculture of One
description: Not as pretentious as it sounds
author:
  name: Greg Sarjeant
timezone: America/New_York
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/gsarjeant/" }
    - { platform: microdotblog, user_url: "https://micro.blog/subcultureofone" }
  header_pages:
    - _pages/about.md